name: projectkost
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  pin_code_fields: ^7.3.0
  flutter_rating_bar: ^4.0.0
  flutter_svg_provider: ^1.0.3
  smooth_page_indicator: ^1.0.0+2
  sms_autofill: ^2.0.0
  outline_gradient_button: ^2.0.0+1
  table_calendar: ^3.0.6
  carousel_slider: ^4.0.0
  intl: ^0.18.0
  connectivity_plus: ^5.0.1
  get: ^4.6.6
  firebase_auth: ^4.14.0
  firebase_database: ^10.3.4
  firebase_storage: ^11.5.1
  image_picker: ^1.0.4
  textfield_datepicker: ^0.2.0
  date_field: ^3.0.5
  equatable: ^2.0.0
  flutter_bloc: ^8.0.0
  url_launcher: ^6.2.1
  flutter_image_slideshow: ^0.1.6
  geolocator: ^8.2.0
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
